site_name: "Mixamo Animation Dumper"
theme:
  name: material # Optional but gives a nice look
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [./src]  # search packages in the src folder
          options:
            show_source: false  # show source code in the documentation
  - pandoc:
      args:
        - "--pdf-engine=xelatex" # Optional, specify a PDF engine
      output_format: pdf # Specify output as LaTeX
